/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary-fixed-dim': '#d2d0ff',
        'on-secondary-container': '#525155',
        'on-primary-fixed-variant': '#4a40e0',
        'on-error-container': '#782232',
        'tertiary-container': '#d2d9f8',
        'primary': '#4d44e3',
        'tertiary-fixed': '#d2d9f8',
        'on-secondary-fixed-variant': '#5c5b5f',
        'on-secondary': '#fcf8fc',
        'outline': '#7b7a7a',
        'on-primary': '#faf6ff',
        'on-tertiary-container': '#444c65',
        'outline-variant': '#b3b2b1',
        'surface-container-highest': '#e4e2e2',
        'secondary-fixed': '#e5e1e6',
        'tertiary': '#575e78',
        'secondary': '#605e62',
        'on-error': '#fff7f7',
        'surface': '#fcf9f8',
        'on-tertiary-fixed': '#323951',
        'inverse-surface': '#0e0e0e',
        'surface-container-lowest': '#ffffff',
        'secondary-container': '#e5e1e6',
        'on-primary-container': '#3f33d6',
        'error-dim': '#4f0116',
        'surface-container-high': '#eae8e7',
        'on-tertiary-fixed-variant': '#4e556f',
        'surface-dim': '#dbdad9',
        'on-background': '#323232',
        'inverse-on-surface': '#9e9c9c',
        'tertiary-dim': '#4b526c',
        'on-primary-fixed': '#2a13c5',
        'surface-variant': '#e4e2e2',
        'on-secondary-fixed': '#403f43',
        'secondary-fixed-dim': '#d7d3d8',
        'surface-bright': '#fcf9f8',
        'on-surface': '#323232',
        'tertiary-fixed-dim': '#c4cbe9',
        'secondary-dim': '#545256',
        'background': '#fcf9f8',
        'error-container': '#ff8b9a',
        'surface-tint': '#4d44e3',
        'on-surface-variant': '#5f5f5f',
        'inverse-primary': '#8582ff',
        'error': '#9e3f4e',
        'primary-container': '#e2dfff',
        'primary-fixed': '#e2dfff',
        'surface-container': '#f0eded',
        'surface-container-low': '#f6f3f2',
        'primary-dim': '#4034d7',
        'on-tertiary': '#faf8ff',
      },
      fontFamily: {
        headline: ['Inter', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
        sans: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
}
